### ISSUE TITLE
Make contact button and page work

### ISSUE THREAD

**Issue by markvoortmanppu** [pointparkuniversity/familyhouse_ios#25]
This is the button at the top right in the app.

**Comment by jeffreyjseamanppu** [comment]
Mark, I have a solution. It's a different solution. Explain later. If you merge my code from my branch, it will all be included. I created the contact view controller and added the page. I've created the contact button on the main page, and removed the call to build it for the other controllers. I think it's a good work around for now and it works. Saves time to focus on more crucial areas.

**Comment by jeffreyjseamanppu** [comment]
Closing this. Client was fine with the work around.
