### ISSUE TITLE
Events Cell Data Images

### ISSUE THREAD

**Issue by jeffreyjseamanppu** [pointparkuniversity/familyhouse_ios#28]
Cell Data Images appear to be able to hold an image and it doesn't match up to the design https://xd.adobe.com/view/d52723dc-308c-4579-5156-23d2da8f0351-a316/screen/e0d77853-c326-4d35-9b00-f62d818b8abf/iPhone-X-XS-11-Pro-5 ( need to review how to do this )

**Comment by markvoortmanppu** [comment]
See https://github.com/pointparkuniversity/familyhouse/issues/2
